/**
 * Tailwind Safelist Generator
 *
 * Generates safelist patterns for dynamically generated Tailwind classes.
 * This ensures that classes generated by design tokens are not purged.
 *
 * Note: Tailwind v4 uses @theme in CSS instead of config files.
 * This file documents the classes that need to be preserved.
 */

/**
 * Color classes that are dynamically generated
 * These patterns ensure all color variants are preserved
 */
export const COLOR_SAFELIST_PATTERNS = [
  // Primary colors
  /^(bg|text|border|ring)-(indigo|blue)-(50|100|200|300|400|500|600|700|800|900|950)$/,

  // Secondary colors
  /^(bg|text|border|ring)-(purple|violet)-(50|100|200|300|400|500|600|700|800|900|950)$/,

  // Success colors
  /^(bg|text|border|ring)-(green|emerald)-(50|100|200|300|400|500|600|700|800|900|950)$/,

  // Warning colors
  /^(bg|text|border|ring)-(yellow|amber)-(50|100|200|300|400|500|600|700|800|900|950)$/,

  // Error colors
  /^(bg|text|border|ring)-(red|rose)-(50|100|200|300|400|500|600|700|800|900|950)$/,

  // Info colors
  /^(bg|text|border|ring)-(cyan|sky)-(50|100|200|300|400|500|600|700|800|900|950)$/,

  // Neutral colors
  /^(bg|text|border|ring)-(gray|slate|zinc|neutral|stone)-(50|100|200|300|400|500|600|700|800|900|950)$/,

  // Hover and focus variants
  /^hover:(bg|text|border)-(indigo|blue|purple|violet|green|emerald|yellow|amber|red|rose|cyan|sky|gray|slate|zinc|neutral|stone)-(50|100|200|300|400|500|600|700|800|900|950)$/,
  /^focus:(bg|text|border|ring)-(indigo|blue|purple|violet|green|emerald|yellow|amber|red|rose|cyan|sky|gray|slate|zinc|neutral|stone)-(50|100|200|300|400|500|600|700|800|900|950)$/,
  /^active:(bg|text|border)-(indigo|blue|purple|violet|green|emerald|yellow|amber|red|rose|cyan|sky|gray|slate|zinc|neutral|stone)-(50|100|200|300|400|500|600|700|800|900|950)$/,
  /^disabled:(bg|text|border|opacity)-(indigo|blue|purple|violet|green|emerald|yellow|amber|red|rose|cyan|sky|gray|slate|zinc|neutral|stone)-(50|100|200|300|400|500|600|700|800|900|950)$/,
] as const;

/**
 * Spacing classes that might be dynamically generated
 */
export const SPACING_SAFELIST_PATTERNS = [
  /^(p|px|py|pt|pr|pb|pl|m|mx|my|mt|mr|mb|ml|gap|space-x|space-y)-(0|1|1\.5|2|2\.5|3|3\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|36|40|44|48|52|56|60|64|72|80|96)$/,
] as const;

/**
 * Typography classes
 */
export const TYPOGRAPHY_SAFELIST_PATTERNS = [
  /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl)$/,
  /^font-(thin|extralight|light|normal|medium|semibold|bold|extrabold|black)$/,
  /^leading-(none|tight|snug|normal|relaxed|loose)$/,
] as const;

/**
 * Radius classes
 */
export const RADIUS_SAFELIST_PATTERNS = [
  /^rounded(-(none|sm|md|lg|xl|2xl|3xl|full))?$/,
  /^rounded-(t|r|b|l|tl|tr|bl|br)-(none|sm|md|lg|xl|2xl|3xl|full)$/,
] as const;

/**
 * All safelist patterns combined
 */
export const TAILWIND_SAFELIST = [
  ...COLOR_SAFELIST_PATTERNS,
  ...SPACING_SAFELIST_PATTERNS,
  ...TYPOGRAPHY_SAFELIST_PATTERNS,
  ...RADIUS_SAFELIST_PATTERNS,
] as const;

/**
 * Documentation for Tailwind v4 configuration
 *
 * In Tailwind v4, safelist is configured via CSS using @theme or @source directives.
 * Since we're using the @tailwindcss/vite plugin (see vite.config.ts and
 * .claude/rules/tokens.md — the PostCSS pipeline is banned), we can add
 * safelist in the CSS file.
 *
 * For dynamic classes, we should ensure they're:
 * 1. Used in component code (so Tailwind detects them)
 * 2. Documented here for reference
 * 3. Added to safelist if absolutely necessary
 *
 * See style.css for @source directive configuration.
 */
