/**
 * no-raw-color-classes — enforces the semantic color vocabulary from
 * .claude/rules/colors.md.
 *
 * Detects:
 *   1. Raw Tailwind color classes like `text-gray-500`, `bg-pink-300`,
 *      `border-slate-200` in component source. The full color list is
 *      taken from the Tailwind primitive palette; the property list is
 *      the union of color-bearing utilities.
 *   2. Arbitrary color syntax like `bg-[var(--color-foo)]` — should use
 *      the native semantic class generated by @theme instead.
 *
 * Exception mechanism (Principle 3 of colors.md): a comment within ~15
 * lines above the offending literal, of one of these shapes, exempts it:
 *   - // exception: <reason>
 *   - // micro-z: <reason> (z-index inline / className pitfall)
 *   - // <the-exact-class>: <reason> (e.g. // bg-pink-300: secondary solid badge)
 */

const COLOR_PROPS =
  "text|bg|border|fill|stroke|ring|outline|divide|placeholder|caret|accent|decoration|shadow";
const COLOR_NAMES =
  "gray|slate|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose";
const COLOR_SHADES = "50|100|200|300|400|500|600|700|800|900|950";

const RAW_REGEX = new RegExp(
  `\\b(${COLOR_PROPS})-(${COLOR_NAMES})-(${COLOR_SHADES})\\b`,
  "g",
);

const ARBITRARY_REGEX = new RegExp(
  `\\b(${COLOR_PROPS})-\\[var\\(--color-[^\\]]+\\)\\]`,
  "g",
);

const EXCEPTION_LOOKBACK_LINES = 15;

function suggestionFor(prop) {
  switch (prop) {
    case "text":
      return "the 'text-fg-*' family";
    case "bg":
      return "the 'bg-surface-*' family";
    case "border":
      return "the 'border-line-*' family";
    case "fill":
    case "stroke":
      return "the 'text-icon-*' family";
    case "ring":
    case "outline":
      return "the 'border-line-focus' / 'border-line-focus-ring' tokens";
    case "shadow":
      return "the semantic shadow tokens";
    default:
      return "the semantic color vocabulary";
  }
}

function commentMatchesException(commentText, className) {
  const text = commentText.trim();
  if (/^exception\s*:/i.test(text)) return true;
  if (/^micro-z\s*:/i.test(text)) return true;
  if (className) {
    const lowered = text.toLowerCase();
    const target = className.toLowerCase() + ":";
    if (lowered.startsWith(target)) return true;
    if (lowered.includes(" " + target)) return true;
  }
  return false;
}

function hasNearbyException(node, sourceCode, className) {
  if (!node.loc) return false;
  const nodeLine = node.loc.start.line;
  const allComments = sourceCode.getAllComments();
  return allComments.some((comment) => {
    if (!comment.loc) return false;
    const endLine = comment.loc.end.line;
    if (endLine < nodeLine - EXCEPTION_LOOKBACK_LINES) return false;
    if (endLine > nodeLine) return false;
    return commentMatchesException(comment.value, className);
  });
}

export default {
  meta: {
    type: "problem",
    docs: {
      description:
        "Disallow raw Tailwind color classes and bg-[var(--color-*)] arbitrary syntax in components. Require the semantic vocabulary from .claude/rules/colors.md, or an inline `// exception: <reason>` comment for Principle 3 cases.",
      recommended: true,
    },
    schema: [],
    messages: {
      rawColorClass:
        "Raw Tailwind color class '{{className}}' is not allowed. Use {{suggestion}} from .claude/rules/colors.md. If this is a legitimate Principle 3 exception, add an inline comment near the literal: // exception: <reason>",
      arbitraryVarSyntax:
        "Arbitrary color syntax '{{className}}' is not allowed. Use the native semantic class generated by @theme (see .claude/rules/colors.md). If this is a legitimate Principle 3 exception, add an inline comment near the literal: // exception: <reason>",
    },
  },
  create(context) {
    const sourceCode = context.sourceCode;

    function checkString(value, node) {
      if (typeof value !== "string" || value.length === 0) return;

      RAW_REGEX.lastIndex = 0;
      let match;
      while ((match = RAW_REGEX.exec(value)) !== null) {
        const className = match[0];
        const prop = match[1];
        if (hasNearbyException(node, sourceCode, className)) continue;
        context.report({
          node,
          messageId: "rawColorClass",
          data: { className, suggestion: suggestionFor(prop) },
        });
      }

      ARBITRARY_REGEX.lastIndex = 0;
      while ((match = ARBITRARY_REGEX.exec(value)) !== null) {
        const className = match[0];
        if (hasNearbyException(node, sourceCode, className)) continue;
        context.report({
          node,
          messageId: "arbitraryVarSyntax",
          data: { className },
        });
      }
    }

    return {
      Literal(node) {
        if (typeof node.value !== "string") return;
        checkString(node.value, node);
      },
      TemplateElement(node) {
        const raw = node.value && (node.value.cooked ?? node.value.raw);
        checkString(raw, node);
      },
    };
  },
};
