/**
 * no-raw-color-classes — enforces the semantic color vocabulary from
 * .claude/rules/colors.md. Real visitor logic lands in the next commit;
 * this scaffold establishes meta + messages so plugin wiring can be
 * built in parallel.
 */
export default {
  meta: {
    type: "problem",
    docs: {
      description:
        "Disallow raw Tailwind color classes and bg-[var(--color-*)] arbitrary syntax in components. Require the semantic vocabulary from .claude/rules/colors.md, or an inline `// exception: <reason>` comment for Principle 3 cases.",
      recommended: true,
    },
    schema: [],
    messages: {
      rawColorClass:
        "Raw Tailwind color class '{{className}}' is not allowed. Use the semantic vocabulary from .claude/rules/colors.md (e.g. {{suggestion}}). If this is a legitimate Principle 3 exception, add an inline comment: // exception: <reason>",
      arbitraryVarSyntax:
        "Arbitrary color syntax '{{className}}' is not allowed. Use the native semantic class generated by @theme (see .claude/rules/colors.md). If this is a legitimate Principle 3 exception, add an inline comment: // exception: <reason>",
    },
  },
  create() {
    return {};
  },
};
